### ISSUE TITLE
Settings-field "sync endpoint" should be named "access url"

### ISSUE THREAD

**Issue by ivh** [misdoro/VAMDC-TAP-Validator#1]
chat-log:

10:12 < ivh> misdoro: in the config-option for the sync-endpoint, one needs to 
             put the url _without_ "sync" since it seems to append sync itself. 
             this might be confusing?
14:54 < misdoro> for sync endpoint you may write anything as long as 
                 capabilities are filled in
15:02 < ivh> I mean the case when I don't want to give the capabilities but 
             only the sync endpoint. (e.g. a test node where the capab does not 
             give the correct /sync)
16:14 < misdoro> and for sync - well, in this field it is meant to be the same 
                 as accessurl in capabilities
16:14 < misdoro> sync and all parameters are added later.
16:16 < ivh> then maybe call this field "access url", not "sync url" ?
16:16 < ivh> but never mind - it's a minor point. :)
16:17 < misdoro> you may file an issue on github? :)

**Comment by misdoro** [comment]
I think this option should be removed completely. A node should always provide a correct capabilities endpoint.
